language: r
cache: packages

warnings_are_errors: false

after_success:
  - travis_wait 35 Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change

addons:
  apt:
    packages:
      - libv8-dev