# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Linear Regression by Cholesky
#' 
#' Do linear regression of form (X^T O X + P)^{-1} X^T y where O is omega, P is
#' precision. 
#' 
#' @keywords internal
#' 
#' @param X Design Matrix
#' @param omega Polya-Gamma weights
#' @param prior_precision Prior Precision for Regression
#' @param y Outcome
LinRegChol <- function(X, omega, prior_precision, y) {
    .Call('_vglmer_LinRegChol', PACKAGE = 'vglmer', X, omega, prior_precision, y)
}

calculate_expected_outer_alpha <- function(L, alpha_mu, re_position_list) {
    .Call('_vglmer_calculate_expected_outer_alpha', PACKAGE = 'vglmer', L, alpha_mu, re_position_list)
}

cpp_zVz <- function(Z, V) {
    .Call('_vglmer_cpp_zVz', PACKAGE = 'vglmer', Z, V)
}

vecR_ridge_general <- function(L, pg_mean, Z, M, mapping_J, d, start_z) {
    .Call('_vglmer_vecR_ridge_general', PACKAGE = 'vglmer', L, pg_mean, Z, M, mapping_J, d, start_z)
}

vecR_design <- function(alpha_mu, Z, M, mapping_J, d, start_z) {
    .Call('_vglmer_vecR_design', PACKAGE = 'vglmer', alpha_mu, Z, M, mapping_J, d, start_z)
}

