# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Linergchol
#' @export
LinRegChol <- function(X, omega, prior_variance, y) {
    .Call('_vglmer_LinRegChol', PACKAGE = 'vglmer', X, omega, prior_variance, y)
}

#' Fast Calculation of E[alpha alpha^T] - Chol
#' @export
chol_calculate_outer_alpha <- function(cholL, P, alpha_mu, re_mu_list, re_group_list, re_position_list) {
    .Call('_vglmer_chol_calculate_outer_alpha', PACKAGE = 'vglmer', cholL, P, alpha_mu, re_mu_list, re_group_list, re_position_list)
}

#' Linergchol
#' @export
GibbsLinRegChol <- function(X, omega, precision, y, stdnorm) {
    .Call('_vglmer_GibbsLinRegChol', PACKAGE = 'vglmer', X, omega, precision, y, stdnorm)
}

#' @export
cyclical_descent_LinReg <- function(X, y, old_eb, cyclical_list, precision_list, sigmasq) {
    .Call('_vglmer_cyclical_descent_LinReg', PACKAGE = 'vglmer', X, y, old_eb, cyclical_list, precision_list, sigmasq)
}

#' @export
calculate_expected_outer_alpha <- function(L, alpha_mu, re_position_list) {
    .Call('_vglmer_calculate_expected_outer_alpha', PACKAGE = 'vglmer', L, alpha_mu, re_position_list)
}

#' @export
vecR_ridge_general <- function(L, pg_mean, Z, M, mapping_J, d, start_z) {
    .Call('_vglmer_vecR_ridge_general', PACKAGE = 'vglmer', L, pg_mean, Z, M, mapping_J, d, start_z)
}

#' @export
vecR_design <- function(alpha_mu, Z, M, mapping_J, d, start_z) {
    .Call('_vglmer_vecR_design', PACKAGE = 'vglmer', alpha_mu, Z, M, mapping_J, d, start_z)
}

